### ISSUE TITLE
Product version in xcp-ng 7.4.1

### ISSUE THREAD

**Issue by yadvr** [xcp-ng/xcp-ng-release#3]
Hi @olivierlambert, in xcp-ng 7.4.1 the iso has product version set to `7.4.0` which is great because then projects like Apache CloudStack don't need to update/check support for any new xcp-ng patch releases if the major (7.4 for example) is already supported.

Can you comment if xcp-ng will continue to retain the same product version (from Citrix XenServer fork) in future, or it can likely change? /cc @PaulAngus @DaanHoogland.

**Comment by olivierlambert** [comment]
Hi!

For now, inside XCP-ng, we'll try follow the exact same version numbering than Citrix (we are working on having 7.5 in XCP-ng). But the update will be trivial (from 7.4 to 7.5), just a `yum update` (or using [XO that does the same from a web UI](https://xen-orchestra.com/blog/xcp-ng-updates-from-xen-orchestra/))

Note we completely ditched the "pack" update system in favor of more classical `yum` thing

**Comment by yadvr** [comment]
Thanks @olivierlambert, my question was more around if you would change the product version (to a minor patch version like 7.4.1, instead of 7.4.0) in the /etc/centos-release (and other xenserver/product branding related config files), not about upgrades.

In case of Apache CloudStack, it discovers the product version of XenServer/XCP-ng using the `/etc/*release` file. For example, this is what I see in case of xcp-ng 7.4.1:
![screenshot from 2018-06-07 11-46-05](https://user-images.githubusercontent.com/95203/41085092-94c306b8-6a53-11e8-9c7b-de88946d3026.png)

**Comment by olivierlambert** [comment]
Does Citrix ever modified the patch number inside XenServer? (`major.minor.patch`). If the answer is no, then we have no intention to do it either. We used `7.4.1` to "increment" our release number because we added some stuff in XCP-ng (like repo, etc.) but it's only a "marketing" decision, nothing changed inside it :+1:

**Comment by yadvr** [comment]
Thanks for answering, I think it will be acceptable to keep the same base product version as Citrix XenServer, that way it will be less effort on our side to support both XS and XCP-ng. I'll close this now.
